import type { Metadata } from "next"; // Importation du type Metadata de Next.js pour la gestion des métadonnées.
import localFont from "next/font/local"; // Importation de la fonction localFont pour utiliser des polices locales dans l'application.
import "./globals.css"; // Importation du fichier CSS global pour appliquer des styles globaux à l'application.
import NavigationMenu from "./components/NavigationMenu"; // Importation du composant de menu de navigation.

const geistSans = localFont({
  src: "./fonts/GeistVF.woff", // Spécification du chemin de la police sans-serif.
  variable: "--font-geist-sans", // Variable CSS pour la police, permettant de l'utiliser dans les styles.
  weight: "100 900", // Définition de la plage de poids de la police.
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff", // Spécification du chemin de la police monospaced.
  variable: "--font-geist-mono", // Variable CSS pour la police monospaced.
  weight: "100 900", // Définition de la plage de poids de la police.
});

// Définition des métadonnées pour la page, comprenant le titre et la description.
export const metadata: Metadata = {
  title: "Create Next App", // Titre de la page, affiché dans l'onglet du navigateur.
  description: "Generated by create next app", // Description de la page, utile pour le référencement.
};

// Composant principal de mise en page de l'application.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // Définition des types pour les enfants du composant (contenu dynamique).
}>) {
  return (
    <html lang="en"> {/* Langue du document HTML définie sur l'anglais. */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} // Application des classes CSS pour les polices et activation de l'anti-aliasing.
      >
        <NavigationMenu /> {/* Rendu du composant de menu de navigation en haut de la page. */}
        {children}  {/* Rendu des enfants passés au composant, permettant l'injection de contenu dynamique. */}
      </body>
    </html>
  );
}
